version: '3.1'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: flumblr:latest
  dev:
    environment:
      - TUMBLR_ACCESS_KEY
      - TUMBLR_SECRET_KEY
    image: flumblr:latest
    ports:
      - 5000:5000
    volumes:
      - ./packages/flumblr:/home/docker/packages/flumblr
      - ./packages/tumblr_auth:/home/docker/packages/tumblr_auth
      - ./docker/bin/cmd:/usr/local/bin/cmd
