version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: flumblr:latest
  dev:
    image: flumblr:latest
    ports: 5000:5000
    volumes:
      - ./app:/home/docker/app
      - ./tumblr_auth:/home/docker/packages/tumblr_auth
